replicaCout: 1
image:
  repository: sunieldevarapu/go-web-app
  pullPolicy: IfNotPresent
  tag: "27747278873"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
